---
# a simpler version of the far superior 
# https://github.com/myllynen/aap-automation/tree/master
#
# installer package is installed on install_host.
# AAP repo  is temporarily enabled. 
# setup is run on install_host. 
# This is the only host with ansible_user SSH private key.

- name: Check access
  hosts: install_host:aapcontrol:aaphub
  gather_facts: false
  become: true
  tasks:
  - name: Ping
    ping:

- name: Copy server certs to localhost
  hosts: aapcontrol:aaphub
  gather_facts: false
  become: true
  tasks:

  # !!! sensitive 
  # use a temporary directory and delete afterwards
  - name: Fetch server certificates for install
    ansible.builtin.fetch:
      src: "/etc/pki/tls/certs/{{ inventory_hostname }}.pem"
      dest: "/var/tmp/"
      flat: yes

  - name: Fetch server keys for install
    ansible.builtin.fetch:
      src: "/etc/pki/tls/private/{{ inventory_hostname }}.key"
      dest: "/var/tmp/"
      flat: yes


- name: AAP install
  hosts: install_host
  gather_facts: true
  become: true
  vars_files:
    - ~/vault-credentials.yml
  vars:
    default_password: Password;1

  tasks:

  # create /opt/ansible-automation-platform/installer/
  - name: Install Ansible Automation Platform installer package
    dnf:
      name: ansible-automation-platform-installer
      enablerepo: ansible-automation-platform-2.4-for-rhel-9-x86_64-rpms
      state: present
    register: r_installer_package

  # !!! sensitive 
  # move passwords to vault
  - name: Configure inventory file
    ansible.builtin.template:
      src: inventory-install-controller-and-hub.ini.j2
      dest: /opt/ansible-automation-platform/installer/inventory
      mode: '0644'

  - name: Before launching setup.sh, check automation controller status
    uri:
      url: "https://{{ groups['aapcontrol'][0] }}/ui/"
      method: GET
      validate_certs: false
    register: r_controller_info
    failed_when: false

  - name: helpful hint
    ansible.builtin.debug:
      msg: 
      - Open a second terminal and run this command. 
      - sudo tail -f /opt/ansible-automation-platform/installer/setup.log

  - name: Let ansible_user write to setup.log
    ansible.builtin.file:
      path: /opt/ansible-automation-platform/installer/setup.log
      owner: ansible_user
      mode: '0644'
      state: touch

  # only run if the controller is not running, or 
  # if the installer package has been updated
  # options
  # lower RAM. Hub doesn't have enough to pass preflight check.
  # also consider -e ignore_preflight_errors=True
  #   cmd:  ./setup.sh -e required_ram=3072
  # Use this to print debug information. 
  #   cmd:  ./setup.sh -- -vvv
  - name: Run setup.sh for controller
    ansible.builtin.shell:
      cmd: > 
        ./setup.sh 
        -e required_ram=3072  
        -- 
        --extra-vars http_proxy=http://gateway.build.example.com:3128  
        --extra-vars https_proxy=http://gateway.build.example.com:3128 
        --extra-vars no_proxy=localhost,127.0.0.1,example.com  
      chdir: /opt/ansible-automation-platform/installer
    environment: 
      ANSIBLE_BECOME: True
      ANSIBLE_NOCOWS: 1
      ANSIBLE_REMOTE_USER: ansible_user
      #ANSIBLE_PRIVATE_KEY_FILE: /home/nick/.ssh/ansible-key.priv
    # my user has SSH keys. Root doesn't.
    become: no
    when: r_installer_package is changed or
          r_controller_info.status != 200
