---
# !!! move to collection roles

# a simpler version of the far superior 
# https://github.com/sscheib/ansible_satellite
# https://blog.scheib.me/2023/07/09/automating-satellite.html
#
# manually created subscription allocation
# https://access.redhat.com/management/subscription_allocations/db350766-32e5-4713-8789-d40dfbe9c969
# subscription allocation can be created using API
# https://access.redhat.com/solutions/6981907
# How to create subscription allocation using the RHSM API?

# !!! todo 
#
# add hostgroup parameter remote_execution_ssh_keys
# add parameter remote_execution_ssh_user for root user
# for foreman_proxy key and ansible_user?
# for "Kickstart finish" provisioning template snippet "remote_execution_ssh_keys"
#
# create libvirt compute resource
# create libvirt compute resource compute profiles
#
# change compute profile CPU mode from default to host-model
# causes rhel 9 provision kernel panic 
#
# change compute profile memory to at least 3096GB
# https://access.redhat.com/solutions/6958349
# Red Hat Satellite Provisioning a RHEL 8.6 system fails with `dracut-initqueue: /lib/dracut-lib.sh: echo: write error: No space left on device
#
# host.build.example.com to id DNS
#
# fix activation key fail
#
# create host collections rhel-8 and rhel-9
# associate with activation keys
#
# add cockpit console to Satellite
# https://www.redhat.com/sysadmin/rhel-web-console-satellite
# https://access.redhat.com/documentation/en-us/red_hat_satellite/6.13/html-single/managing_hosts/index#Host_Management_and_Monitoring_Using_Cockpit_managing-hosts
#
# enable Satellite Client 6 repository 
# install tracer 
# https://access.redhat.com/documentation/en-us/red_hat_satellite/6.13/html-single/managing_hosts/index#enabling-tracer-on-a-host_managing-hosts
#
# add ccv- composite content views for baseos, appstream and sat client
# change hg- host groups to use ccv-
#

- name: Satellite config 
  hosts: satellite
  gather_facts: true  # required for the role redhat.satellite_operations.installer
  become: true  # required for the role redhat.satellite_operations.installer
  vars_files:
    - ~/vault-credentials.yml
  environment:
    http_proxy: "http://gateway.{{ lab_domain }}:3128"
    HTTPS_PROXY: "http://gateway.{{ lab_domain }}:3128"
    no_proxy: localhost,127.0.0.1,example.com
  roles:

      # These values are set in host_vars.
        # satellite_server_url: "{{ sat_server_url }}"
        # satellite_username: "{{ sat_admin_user }}"
        # satellite_password: "{{ sat_admin_pass }}"
        # satellite_organization: "{{ sat_organization }}"


      # 10
      # domains
    - role: redhat.satellite.domains
      vars:
        satellite_domains:
          - name: "build.example.com"
            description: "Build Domain"
            locations:
              - "{{ sat_location }}"
            organizations:
              - "{{ sat_organization }}"

      # 11
      # subnets
    - role: redhat.satellite.subnets
      vars:
        satellite_subnets:
          - name: 'sn-build-subnet'
            network: "{{ lab_net_prefix }}.0"
            mask: '255.255.255.0'
            gateway: "{{ lab_net_prefix }}.1"
            ipam: 'DHCP'
            boot_mode: "DHCP"
            from_ip: "{{ lab_net_prefix }}.100"
            to_ip: "{{ lab_net_prefix }}.199"
            dhcp_proxy: '{{ inventory_hostname }}'
            tftp_proxy: '{{ inventory_hostname }}'
            template_proxy: '{{ inventory_hostname }}'
            discovery_proxy: '{{ inventory_hostname }}'
            remote_execution_proxies:
              - '{{ inventory_hostname }}'
            dns_primary: "{{ lab_net_prefix }}.4"
            domains:
              - "build.example.com"
            organizations:
              - '{{ sat_organization }}'
            locations:
              - '{{ sat_location }}'

      # 17
      # activation keys
      # https://access.redhat.com/documentation/en-us/red_hat_satellite/6.13/html/managing_content/managing_activation_keys_content-management
      # https://console.redhat.com/ansible/automation-hub/repo/published/redhat/satellite/content/role/activation_keys/
    - role: redhat.satellite.activation_keys
      vars:
        satellite_activation_keys: "{{ sat_activation_keys }}"

      # 18
      # hostgroups
    - role: redhat.satellite.hostgroups
      vars:
        satellite_hostgroups:
            # console > Configure > Host Groups > Create Host Group > Host Group
          - name: "hg-rhel-8"
            organization: '{{ sat_organization }}'
            description: "RHEL 8 hostgroup"
            lifecycle_environment: 'lce-build'
            content_view: 'cv-rhcdn-base-rhel-8'
            content_source: '{{ inventory_hostname }}'
            openscap_proxy: '{{ inventory_hostname }}'
            # console > Configure > Host Groups > Create Host Group > Network
            domain: 'build.example.com'
            subnet: 'sn-build-subnet'
            # console > Configure > Host Groups > Create Host Group > Operating System
            architecture: "x86_64"
            operatingsystem: "RHEL 8.8"
            kickstart_repository: 'Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.8'
            ptable: "Kickstart default"
            pxe_loader: 'PXELinux BIOS'
            root_pass: 'Password;1'
            # console > Configure > Host Groups > Create Host Group > Locations, Organizations, Activation Keys
            locations:
              - '{{ sat_location }}'
            organizations:
              - '{{ sat_organization }}'
            activation_keys: 
              - 'ak-build-rhel-8'

            # console > Configure > Host Groups > Create Host Group > Host Group
          - name: "hg-rhel-9"
            organization: '{{ sat_organization }}'
            description: "RHEL 9 hostgroup"
            lifecycle_environment: 'lce-build'
            content_view: 'cv-rhcdn-base-rhel-9'
            content_source: '{{ inventory_hostname }}'
            openscap_proxy: '{{ inventory_hostname }}'
            # console > Configure > Host Groups > Create Host Group > Network
            domain: 'build.example.com'
            subnet: 'sn-build-subnet'
            # console > Configure > Host Groups > Create Host Group > Operating System
            architecture: "x86_64"
            operatingsystem: "RedHat 9.2"
            kickstart_repository: 'Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.2'
            ptable: "Kickstart default"
            pxe_loader: 'PXELinux BIOS'
            root_pass: 'Password;1'
            # console > Configure > Host Groups > Create Host Group > Locations, Organizations, Activation Keys
            locations:
              - '{{ sat_location }}'
            organizations:
              - '{{ sat_organization }}'
            activation_keys: 
              - 'ak-build-rhel-9'
