---
# These values override defaults.
# default variables and their values are listed here.
#   https://github.com/nickhardiman/ansible-collection-platform/blob/main/roles/libvirt_machine_kickstart/defaults/main.yml

# virt-install
# default RHEL 9

# compute
# default 2 cores
# default 4GiB memory

# storage
# default 30GB disk

# network
# MAC addresses are listed here.
#   https://github.com/nickhardiman/ansible-playbook-build/blob/main/README.adoc
nics:
-
  name: enp1s0
  mac: "{{ lab_supply_mac_prefix }}:00:04"
  net: "{{ lab_supply_libvirt_name }}"
  # !!! get rid of this?
  # used in
  # ansible_collections/nick/platform/roles/hosts_record/tasks/main.yml
  # interface IP provided by DHCP, prob. shouldnt be here too.
  ip: "{{ lab_supply_net_prefix }}.4"

# firewall
# Command 'firewall-offline-cmd' uses XML files in /usr/lib/firewalld/services/.
net_services:
  - ssh
  - freeipa-4

# OS
host: idreplica
fqdn: "{{ host }}.{{ lab_supply_domain }}"
RPMs:
  - cockpit
  - ipa-server
  - ipa-server-dns

# kickstart
kickstart_template: "kvm-guest-nic-static.ks.j2"
