---
# virt-install
# These values override defaults.
# default variables and their values are listed here. 
#   https://github.com/nickhardiman/ansible-collection-platform/blob/main/roles/libvirt_machine_kickstart/defaults/main.yml

# compute 
# default 2 cores
# default 4GiB memory

# storage
# default 30GB disk

# network
nics:
- 
  name: enp1s0
  mac: "{{ lab_supply_mac_prefix }}:00:07"
  net: "{{ lab_supply_libvirt_name }}"
  ip: "{{ lab_supply_net_prefix }}.7"

net_services:
- http
- https
- ssh

# OS
host: git
fqdn: "{{ host }}.{{ lab_supply_domain }}"
RPMs:
    - curl
    - openssh-server
    - openssl
    - postfix
    - tzdata

# kickstart
kickstart_template: "kvm-guest-nic-static.ks.j2"

# app
gitlab_domain: "git.{{ lab_supply_domain }}"
gitlab_ssl_certificate: "/etc/pki/tls/certs/{{ gitlab_domain }}.pem"
gitlab_ssl_certificate_key: "/etc/pki/tls/private/{{ gitlab_domain }}.key"
gitlab_create_self_signed_cert: no
gitlab_extra_settings:
  - gitlab_rails:
      - key: "env"
        type: "plain"
        value: |
          {
          "http_proxy" => "https://{{ lab_supply_net_prefix }}.3:3128",
          "https_proxy" => "https://{{ lab_supply_net_prefix }}.3:3128",
          "no_proxy" => "localhost, 127.0.0.1, example.com"
          }
