---
# network
# Names and addresses are partially set in variables below.
# A full list is here.
#   https://github.com/nickhardiman/ansible-playbook-supply/tree/main
# For the remaining parts of these names and addresses, see each host's vars file eg.
#   host_vars/gateway.supply.example.com/main.yml
# Note the suffix "." on domain names.
#
# nework identifiers
# 10 - source public 
# 11 - source private 
# 12 - build public 
# 13 - build private 
# 14 - supply public 
# 15 - supply private 

public_net_short_name: public
public_libvirt_name:   "net{{ public_net_short_name }}0"
public_mac_prefix:     "52:54:00:14"
public_nmcli_name:     "bridge-{{ public_net_short_name }}0"
public_bridge_name:    "br{{ public_net_short_name }}0"

# !!! start of refactor to have many sets of network variables (source, build, and supply)
# !!! Changing address means changing a few variables. eg.
# "11" appears in three places here.
lab_supply_net_short_name: supply
lab_supply_libvirt_name:   "net{{ lab_supply_net_short_name }}0"
lab_supply_net_prefix:     "192.168.15"
lab_supply_mac_prefix:     "52:54:00:15"
lab_supply_domain:         "{{ lab_supply_net_short_name }}.example.com"
# DNS Zone names in IPA Server
lab_supply_domain_forward: "{{ lab_supply_domain }}."
lab_supply_domain_reverse: "15.168.192.in-addr.arpa."

# !!! ansible-collection-platform needs reworking
lab_net_short_name: "{{ lab_supply_net_short_name }}"
lab_net_prefix: "{{ lab_supply_net_prefix }}"
lab_mac_prefix: "{{ lab_supply_mac_prefix }}"
lab_libvirt_name:   "net{{ lab_net_short_name }}0"
lab_nmcli_name: "bridge-{{ lab_net_short_name }}0"
lab_bridge_name:     "br{{ lab_net_short_name }}0"
lab_bridge_mac:        "{{ lab_mac_prefix }}:00:01"
lab_bridge_ip_cidr:    "{{ lab_net_prefix }}.1/24"
lab_domain: "{{ lab_supply_domain }}"
# DNS Zone names in IPA Server
lab_domain_forward: "{{ lab_supply_domain_forward }}"
lab_domain_reverse: "{{ lab_supply_domain_reverse }}"

# !!! place this in the vault 
# replace the many values in nick.platform roles with "{{ default_password }}"
default_password: 'Password;1'
