---
# virt-install
# These values override defaults.
# default variables and their values are listed here. 
#   https://github.com/nickhardiman/ansible-collection-platform/blob/main/roles/libvirt_machine_kickstart/defaults/main.yml

# compute 
cpus: 4
# size in MiB
ram: 8192

# storage
# default 30GB disk

# network
nics:
- 
  name: enp1s0
  mac: "{{ lab_supply_mac_prefix }}:00:08"
  net: "{{ lab_supply_libvirt_name }}"
  ip: "{{ lab_supply_net_prefix }}.8"

net_services:
  - http
  - https
  - ssh
  - grafana
  - prometheus

# OS
host: monitor
fqdn: "{{ host }}.{{ lab_supply_domain }}"
RPMs:
  - httpd
  - python3-jmespath
  - python3-libselinux
  - python3-libsemanage
  - python3-pip
  - python3-policycoreutils

# kickstart
kickstart_template: "kvm-guest-nic-static.ks.j2"
