# a simpler version of the far superior 
# https://github.com/sscheib/ansible_satellite
# https://blog.scheib.me/2023/07/09/automating-satellite.html

# many things are defined inline in the playbook. 

# credentials and more
sat_server_url: "https://satellite.{{ lab_domain }}"
sat_admin_user: "admin"
sat_admin_pass: "Password;1"
sat_organization: Default Organization
sat_location: Default Location
# facts for redhat.satellite roles
satellite_server_url: "{{ sat_server_url }}"
satellite_username: "{{ sat_admin_user }}"
satellite_password: "{{ sat_admin_pass }}"
satellite_organization: "{{ sat_organization }}"

sat_products: 
  - name: 'Red Hat Enterprise Linux for x86_64'
    repository_sets:
      - name: 'Red Hat Enterprise Linux 9 for x86_64 - BaseOS (RPMs)'
        releasever: 9
        download_policy: 'on_demand'
      - name: 'Red Hat Enterprise Linux 9 for x86_64 - AppStream (RPMs)'
        releasever: 9
        download_policy: 'on_demand'
      - name: 'Red Hat Enterprise Linux 9 for x86_64 - BaseOS (Kickstart)'
        releasever: 9.2
        download_policy: 'immediate'
      - name: 'Red Hat Enterprise Linux 9 for x86_64 - AppStream (Kickstart)'
        releasever: 9.2
        download_policy: 'immediate'
      - name: 'Red Hat Satellite Client 6 for RHEL 9 x86_64 (RPMs)'
        download_policy: 'on_demand'
      - name: 'Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)'
        releasever: 8
        download_policy: 'on_demand'
      - name: 'Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)'
        releasever: 8
        download_policy: 'on_demand'
      - name: 'Red Hat Enterprise Linux 8 for x86_64 - BaseOS (Kickstart)'
        releasever: 8.8
        download_policy: 'immediate'
      - name: 'Red Hat Enterprise Linux 8 for x86_64 - AppStream (Kickstart)'
        releasever: 8.8
        download_policy: 'immediate'
      - name: 'Red Hat Satellite Client 6 for RHEL 8 x86_64 (RPMs)'
        download_policy: 'on_demand'
  - name: 'Red Hat Ansible Automation Platform'
    repository_sets:
      - name: 'Red Hat Ansible Automation Platform 2.4 for RHEL 8 x86_64 (RPMs)'
        download_policy: 'on_demand'
      - name: 'Red Hat Ansible Automation Platform 2.4 for RHEL 9 x86_64 (RPMs)'
        download_policy: 'on_demand'

sat_lifecycle_environments:
  - name: 'lce-build'
    prior: 'Library'
  - name: 'lce-deploy'
    prior: 'lce-build'


sat_content_views:
  - name: 'cv-rhcdn-base-rhel-8'
    lifecycle_environments: "{{ sat_lifecycle_environments | map(attribute='name') }}"
    repositories:
        # no lifecycle_environments list - publish to all lifecycle envs
      - name: 'Red Hat Enterprise Linux 8 for x86_64 - BaseOS RPMs 8'
        product: 'Red Hat Enterprise Linux for x86_64'

      - name: 'Red Hat Enterprise Linux 8 for x86_64 - AppStream RPMs 8'
        product: 'Red Hat Enterprise Linux for x86_64'

      - name: 'Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.8'
        product: 'Red Hat Enterprise Linux for x86_64'

      - name: 'Red Hat Enterprise Linux 8 for x86_64 - AppStream Kickstart 8.8'
        product: 'Red Hat Enterprise Linux for x86_64'

  - name: 'cv-rhcdn-base-rhel-9'
    lifecycle_environments: "{{ sat_lifecycle_environments | map(attribute='name') }}"
    repositories:
      - name: 'Red Hat Enterprise Linux 9 for x86_64 - BaseOS RPMs 9'
        product: 'Red Hat Enterprise Linux for x86_64'

      - name: 'Red Hat Enterprise Linux 9 for x86_64 - AppStream RPMs 9'
        product: 'Red Hat Enterprise Linux for x86_64'

      - name: 'Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.2'
        product: 'Red Hat Enterprise Linux for x86_64'

      - name: 'Red Hat Enterprise Linux 9 for x86_64 - AppStream Kickstart 9.2'
        product: 'Red Hat Enterprise Linux for x86_64'

  - name: 'cv-rhcdn-satellite_6_client-rhel-8'
    repositories:
      - name: 'Red Hat Satellite Client 6 for RHEL 8 x86_64 RPMs'
        product: 'Red Hat Enterprise Linux for x86_64'

  - name: 'cv-rhcdn-satellite_6_client-rhel-9'
    repositories:
      - name: 'Red Hat Satellite Client 6 for RHEL 9 x86_64 RPMs'
        product: 'Red Hat Enterprise Linux for x86_64'
    # empty lifecycle_environments list - publish to no lifecycle envs
  - name: 'cv-rhcdn-ansible_automation_platform-rhel-8'
    lifecycle_environments: []
    repositories:
      - name: 'Red Hat Ansible Automation Platform 2.4 for RHEL 8 x86_64 RPMs'
        product: 'Red Hat Ansible Automation Platform'

  - name: 'cv-rhcdn-ansible_automation_platform-rhel-9'
    lifecycle_environments: []
    repositories:
      - name: 'Red Hat Ansible Automation Platform 2.4 for RHEL 9 x86_64 RPMs'
        product: 'Red Hat Ansible Automation Platform'


sat_activation_keys:
  - name: 'ak-build-rhel-8'
    description: "All hosts which don't have a specialized host group"
    lifecycle_environment: 'lce-build'
    content_view: 'cv-rhcdn-base-rhel-8'
    release_version: 8
    unlimited_hosts: true
    service_level: 'Self-Support'
    purpose_usage: 'Development/Test'
    purpose_role: 'Red Hat Enterprise Linux Server'
    content_overrides:
      - label: 'satellite-client-6-for-rhel-8-x86_64-rpms'
        override: 'enabled'

  - name: 'ak-build-rhel-9'
    description: "All hosts which don't have a specialized host group"
    lifecycle_environment: 'lce-build'
    content_view: 'cv-rhcdn-base-rhel-9'
    release_version: 9
    unlimited_hosts: true
    service_level: 'Self-Support'
    purpose_usage: 'Development/Test'
    purpose_role: 'Red Hat Enterprise Linux Server'
    content_overrides:
      - label: 'satellite-client-6-for-rhel-9-x86_64-rpms'
        override: 'enabled'
